//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fmsFile
    {
        public int FileID { get; set; }
        public int FileType { get; set; }
        public string FileNumber { get; set; }
        public int FileVolumnNumber { get; set; }
        public string FileRemarks { get; set; }
        public int FileInitiatedBy { get; set; }
    }
}
