//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageIn
    {
        public int id { get; set; }
        public string sender { get; set; }
        public string msg { get; set; }
        public Nullable<System.DateTime> senttime { get; set; }
        public string receivedtime { get; set; }
    }
}
