//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int ResourceID { get; set; }
        public string MobileNumber { get; set; }
        public string ResourceName { get; set; }
        public int ResourceCategoryID { get; set; }
    }
}
