//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotification
    {
        public int ID { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public Nullable<int> ParameterID { get; set; }
        public Nullable<int> ParameterValue { get; set; }
        public string Comment { get; set; }
        public Nullable<int> forUser { get; set; }
        public Nullable<int> fromUser { get; set; }
        public Nullable<System.DateTime> notificationTime { get; set; }
        public Nullable<int> markRead { get; set; }
        public Nullable<System.DateTime> readTime { get; set; }
    }
}
