//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParamForm1
    {
        public int ID { get; set; }
        public int ResourceID { get; set; }
        public int ParameterID { get; set; }
        public string Formala { get; set; }
        public int CompanyID { get; set; }
    
        public virtual tblParameter tblParameter { get; set; }
        public virtual tblResource tblResource { get; set; }
    }
}
