//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParameter
    {
        public tblParameter()
        {
            this.tblEnergies = new HashSet<tblEnergy>();
            this.tblTemplateParameters = new HashSet<tblTemplateParameter>();
            this.tblParamForms1 = new HashSet<tblParamForm1>();
        }
    
        public int ParameterID { get; set; }
        public string ParameterName { get; set; }
        public int ParameterOrder { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Mainformula { get; set; }
    
        public virtual ICollection<tblEnergy> tblEnergies { get; set; }
        public virtual ICollection<tblTemplateParameter> tblTemplateParameters { get; set; }
        public virtual ICollection<tblParamForm1> tblParamForms1 { get; set; }
    }
}
