//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResource
    {
        public tblResource()
        {
            this.tblEnergies = new HashSet<tblEnergy>();
            this.tblParamForms1 = new HashSet<tblParamForm1>();
            this.tblResourceSchedulers1 = new HashSet<tblResourceScheduler1>();
        }
    
        public int ResourceID { get; set; }
        public string MobileNumber { get; set; }
        public string ResourceLocation { get; set; }
        public int TemplateID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CooridatesGoogle { get; set; }
        public string resourceName { get; set; }
    
        public virtual ICollection<tblEnergy> tblEnergies { get; set; }
        public virtual tblTemplate tblTemplate { get; set; }
        public virtual ICollection<tblParamForm1> tblParamForms1 { get; set; }
        public virtual ICollection<tblResourceScheduler1> tblResourceSchedulers1 { get; set; }
    }
}
