//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRemoteSensor
    {
        public int ID { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public Nullable<bool> ModeManualAuto { get; set; }
        public Nullable<bool> PreviousMotorOnOffStatus { get; set; }
        public Nullable<bool> CurrentMotorOnOffStatus { get; set; }
    }
}
