//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResourceScheduler1
    {
        public int ScheduleID { get; set; }
        public int ResourceID { get; set; }
        public Nullable<System.DateTime> ScheduleTimeFrom { get; set; }
        public Nullable<System.DateTime> ScheduleTimeTo { get; set; }
        public int CompanyID { get; set; }
    
        public virtual tblResource tblResource { get; set; }
    }
}
