//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplate
    {
        public tblTemplate()
        {
            this.tblResources = new HashSet<tblResource>();
            this.tblTemplateParameters = new HashSet<tblTemplateParameter>();
        }
    
        public int TemplateID { get; set; }
        public string TemplateName { get; set; }
        public int ParameterCount { get; set; }
        public string Separator { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual ICollection<tblResource> tblResources { get; set; }
        public virtual ICollection<tblTemplateParameter> tblTemplateParameters { get; set; }
    }
}
