//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplateParameter
    {
        public int ID { get; set; }
        public int TemplateID { get; set; }
        public Nullable<int> ParameterID { get; set; }
        public int ParameterOrder { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual tblParameter tblParameter { get; set; }
        public virtual tblTemplate tblTemplate { get; set; }
    }
}
