//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueParameter
    {
        public int id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string name { get; set; }
        public string mobileNumber { get; set; }
        public string VP1 { get; set; }
        public string VP2 { get; set; }
        public string VP3 { get; set; }
        public string VP4 { get; set; }
        public string VP5 { get; set; }
        public string VP6 { get; set; }
        public string VP7 { get; set; }
        public string VP8 { get; set; }
        public string VP9 { get; set; }
        public string VP10 { get; set; }
        public string VP11 { get; set; }
        public string VP12 { get; set; }
        public string VP13 { get; set; }
        public string VP14 { get; set; }
        public string VP15 { get; set; }
        public string VP16 { get; set; }
        public string VP17 { get; set; }
    }
}
