//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models.Models_RMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ttlogixc_rmsWasa01Entities : DbContext
    {
        public ttlogixc_rmsWasa01Entities()
            : base("name=ttlogixc_rmsWasa01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCompany> tblCompanies { get; set; }
        public DbSet<tblParameter> tblParameters { get; set; }
        public DbSet<tblResource> tblResources { get; set; }
        public DbSet<tblResourceType> tblResourceTypes { get; set; }
        public DbSet<tblResourceTypeParameter> tblResourceTypeParameters { get; set; }
        public DbSet<tblSheet> tblSheets { get; set; }
        public DbSet<tblSubResource> tblSubResources { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
    }
}
